### ISSUE TITLE
Attempt to read from field 'android.graphics.Paint ch.logixisland.anuto.entity.effect.TeleportEffect$StaticData.mPaint' on a null object reference

### ISSUE THREAD

**Issue by Massedil** [mjaun/android-anuto#202]
I quickly report a crash, I hope it helps.

Don't know how to reproduce, but I was testing the game with a x16 speed accelerator and loading a new wage with the last one still here. So with a lot of enemies on screen and moving fast.

The progression is lost in that case.

```
03-21 12:25:04.333 E/AndroidRuntime(14982): FATAL EXCEPTION: main
03-21 12:25:04.333 E/AndroidRuntime(14982): Process: ch.logixisland.anuto, PID: 14982
03-21 12:25:04.333 E/AndroidRuntime(14982): java.lang.NullPointerException: Attempt to read from field 'android.graphics.Paint ch.logixisland.anuto.entity.effect.TeleportEffect$StaticData.mPaint' on a null object reference
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at ch.logixisland.anuto.entity.effect.TeleportEffect$StaticData.access$200(TeleportEffect.java:18)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at ch.logixisland.anuto.entity.effect.TeleportEffect$TeleportDrawable.draw(TeleportEffect.java:34)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at ch.logixisland.anuto.engine.render.Renderer.draw(Renderer.java:82)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at ch.logixisland.anuto.view.game.GameView.onDraw(GameView.java:66)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.View.draw(View.java:22350)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.View.updateDisplayListIfDirty(View.java:21226)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.View.updateDisplayListIfDirty(View.java:21186)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.Choreographer.doFrame(Choreographer.java:731)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.os.Handler.handleCallback(Handler.java:938)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.os.Looper.loop(Looper.java:223)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at java.lang.reflect.Method.invoke(Native Method)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-21 12:25:04.333 E/AndroidRuntime(14982): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by mjaun** [comment]
Could you tell which app version you were using? This issue should be fixed in version 0.9-1.

**Comment by Massedil** [comment]
I was using the 0.9 version, not the 0.9-1.
